[package]
name = "input-server"
version = "0.1.0"
edition = "2021"

[features]
default = []
proptest = []

[dependencies]
nix.workspace = true
odilia-common.workspace = true
rdev = { git = "https://github.com/TTWNO/rdev/", branch = "odilia-keys-v2", features = ["unstable_grab"] }
serde_json.workspace = true
tracing.workspace = true

[dev-dependencies]
atspi-common.workspace = true
proptest = "1.6.0"
