[build]
pre-build = [
	"apt update",
	# libevdev-dev for `evdev` headers
	# linux-header-generic for access to linux/types.h (also required for evdev)
	# clang for rust compiler
	"apt install -y libevdev-dev linux-headers-generic clang",
]
