[target.aarch64-unknown-linux-gnu]
pre-build = [
	"apt update",
	"apt install -y libevdev-dev linux-headers-generic python",
]

[target.aarch64-unknown-linux-musl]
pre-build = [
	"apt update",
	"apt install -y libevdev-dev linux-headers-generic python",
]

[target.x86_64-unknown-linux-gnu]
pre-build = [
	"apt update",
	"apt install -y libevdev-dev linux-headers-generic python",
]

[target.x86_64-unknown-linux-musl]
pre-build = [
	"apt update",
	"apt install -y libevdev-dev linux-headers-generic python",
]

