#!/bin/sh

export RUST_LOG=none
~/.cargo/bin/odilia&
echo "for extended keyboard functionality, type your password at the prompt below. If you don't want that for whatever reason, maybe because the hotkey daemon is already running, send sigint to the terminal, for example by pressing ctrl+c"
#this should start the sohkd daemon, but for whatever reason it doesn't work on my machine
#source ./start-sohkd.sh &
#therefore, I'm coppying the contents of that script here
pkttyagent -p $(echo $$) | pkexec env XDG_CONFIG_HOME=$XDG_CONFIG_HOME XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR ~/.cargo/bin/sohkd --config /etc/odilia/sohkdrc 
